export const TRANSPORTER_LIST_REQUEST = 'TRANSPORTER_LIST_REQUEST';

export const TRANSPORTER_LIST_SUCCESS = 'TRANSPORTER_LIST_SUCCESS';

export const TRANSPORTER_LIST_FAIL = 'TRANSPORTER_LIST_FAIL';



