export const TRANSPORTER_LIST_REQUEST = 'TRANSPORTER_LIST_REQUEST';

export const TRANSPORTER_LIST_SUCCESS = 'TRANSPORTER_LIST_SUCCESS';

export const TRANSPORTER_LIST_FAIL = 'TRANSPORTER_LIST_FAIL';

export const TRANSPORTER_DETAILS_REQUEST = 'TRANSPORTER_DETAILS_REQUEST';

export const TRANSPORTER_DETAILS_SUCCESS = 'TRANSPORTER_DETAILS_SUCCESS';

export const TRANSPORTER_DETAILS_FAIL = 'TRANSPORTER_DETAILS_FAIL';


